language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install gcc libffi-dev libldap2-dev libsasl2-dev libssl-dev python-dev
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: opennode
  password:
    secure: i8ExSjuAimfw80b6lr4NDvvWa5Eiw42I1AbEvqhzFIgOBqqYlbG8CZBpoUSrIfTgMr2VCkbyMt2jfNGE1eiX0JBWJWJDs9ucA3EUKz6rc/P6BAILp9E6K1hOZVHb2c4W5XBlp+b54xnZqIvP9BxUiat+rOaCoTQOfBJD2Em8j0ph/K2EDg/MkpGMe5fIKaOMZS+Jw7Tkb6W+RNcJlTePM1HCImuG6/onwVRblv9dhE94C5AHxEFSpgP6/0set1ehCmY9fZbSdrZFziwCGVENsGS5taKK11M5xPfX0vWM16x1x2meFsGyiKyryYLrLKgjLKRJ+IxjazU8zUpXEmQxR7rKBK1DlxQU75jx70CTldhQf/Kr7LjYED9okQuOMdx3Mdz0eMs1S4Ww+6rSwn36/UnV7PHGzlsu/YDyp/KXLiWLSH2QgnvYMCEu3DQUc441ZzxmYn94lVJpLiA5FnrV7to/qy1lTWW78QWme7I0ggR75FerKM4zmjXSE6XN6EnU77SOKS7j7LtAnxomdZJCAuyrFhS6bLRx5gOItA2xvnxGLic+Qol40shxjNTvXTNuddJ1xtoYtOg5UCL1su0wNwENipJIy9PUAX+8FSWTgEqI8O4DtLrulQDDGHrWn30iVsWCRPDldzi9KCzYiMBBdBZmdTlOxEvyTRHQIs3i6yI=
  on:
    tags: true
    repo: opennode/nodeconductor-saml2
